sudo: required
services:
  - docker

before_install:
  - docker build -t pranith05/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true pranith05/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-081445444514"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secure_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true